### ISSUE TITLE
Become familiar with React Native

### ISSUE THREAD

**Issue by guyu96** [guyu96/chordinate#1]
Go through the tutorial and guides at:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by CynthiaTong** [comment]
[React Native Essential Training](https://www.lynda.com/React-Native-tutorials/React-Native-Essential-Training/560343-2.html?srchtrk=index%3a1%0alinktypeid%3a2%0aq%3areact+native%0apage%3a1%0as%3arelevance%0asa%3atrue%0aproducttypeid%3a2)

**Comment by guyu96** [comment]
Link to the course we purchased: https://www.udemy.com/react-native-the-practical-guide/

I think we know enough about React Native now.
