### ISSUE TITLE
Implement the chord progression selection view

### ISSUE THREAD

**Issue by CynthiaTong** [guyu96/chordinate#4]
Include the following child components: 
* chord name, quality, duration (scrollable) list
* drag-and-drop timeline
* piano chord visualization
* bpm slider
* add, start buttons

**Comment by RocketPlumber** [comment]
BTW, for storing chord progressions: https://github.com/andpor/react-native-sqlite-storage ? https://facebook.github.io/react-native/docs/asyncstorage.html ?

**Comment by RocketPlumber** [comment]
ok after talking to Guyu going forward with asyncstorage
